---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: main-source-git-shmardt-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://gitlab.com/my-kicas-group/shmardt-app.git
